version: '3.9'

services:
  # Backend
  test-db:
    container_name: test-db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_TEST_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:-test}
      POSTGRES_DB: ${POSTGRES_TEST_DATABASE:-test-hubbl-db}
      PGDATA: /data/postgres
    # Volume should not be persisted
    ports:
      - 5433:5432
    restart: unless-stopped
    profiles: ['all', 'dev', 'test']

  # Has no profiles since it is always required
  postgres:
    container_name: dev-db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

  # Api
  api-dev:
    container_name: hubbl-api-dev
    image: node:16.10.0-alpine3.14
    volumes:
      - .:/app
    command:
      - /bin/sh
      - -c
      - |
        apk add git
        cd /app
        npx nx serve api
    ports:
      - 3333:3333
    networks:
      - postgres
    profiles: ['all', 'dev']
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
