version: '3.9'

services:
  # Nginx proxy to serve applications
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped

  # Backend
  test-db:
    container_name: test-db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_TEST_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:-test}
      POSTGRES_DB: ${POSTGRES_TEST_ATABASE:-test-hubbl-db}
      PGDATA: /data/postgres
    # Volume should not be persisted
    ports:
      - 5433:5432
    restart: unless-stopped
    profiles: ['all', 'dev', 'test']

  # Has no profiles since it is always required
  postgres:
    container_name: dev-db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DATABASE:-hubbl-db}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

  # Api
  api-dev:
    container_name: hubbl-api-dev
    image: node:16.14.2-alpine3.14
    volumes:
      - .:/app
    command:
      - /bin/sh
      - -c
      - |
        apk add git
        cd /app
        npm install
        npx nx serve api
    ports:
      - 3333:3333
    networks:
      - postgres
    mem_limit: 1G
    restart: unless-stopped
    profiles: ['all', 'dev']
    
  # Core
  core-dev:
    container_name: hubbl-core-dev
    image: node:16.14.2-alpine3.14
    volumes:
      - .:/app
    command:
      - /bin/sh
      - -c
      - |
        apk add git
        cd /app
        npm install
        npx nx serve core
    ports:
      - 4200:4200
    expose:
      - 4200
    networks:
      - postgres
    environment:
      VIRTUAL_HOST: core.hubbl.local
      VIRTUAL_PORT: 4200
    restart: unless-stopped
    mem_limit: 2G
    profiles: ['all', 'dev']
    
  client-dev:
    container_name: hubbl-client-dev
    image: node:16.14.2-alpine3.14
    volumes:
      - .:/app
    command:
      - /bin/sh
      - -c
      - |
        apk add git
        cd /app
        npm install
        npx nx serve client
    ports:
      - 4201:4201
    expose:
      - 4201
    networks:
      - postgres
    environment:
      VIRTUAL_HOST: client.hubbl.local
      VIRTUAL_PORT: 4201
    restart: unless-stopped
    mem_limit: 2G
    profiles: ['all', 'dev']

networks:
  default:
    name: nginx-proxy
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
