  name: CI Core
  on:
    push:
      branches:
        - 'develop'
      paths:
        - 'apps/core/**'
    pull_request:
      paths:
        - 'apps/core/**'

  jobs:
    ci-develop:
      runs-on: ubuntu-latest
      if: ${{ github.event_name != 'pull_request' }}
      steps:
        - uses: actions/checkout@v2
          name: Checkout [develop]
          with:
            fetch-depth: 0
        - uses: ./.github/actions/ci
          name: Running CI on a push
          with:
            proj-name: 'core'
            codecov-token: ${{ secrets.CODECOV_TOKEN }}

    ci-pr:
      runs-on: ubuntu-latest
      if: ${{ github.event_name == 'pull_request' }}
      steps:
        - uses: actions/checkout@v2
          name: Checkout [develop]
          with:
            fetch-depth: 0
        - uses: ./.github/actions/ci
          name: Running CI on a pull request
          with:
            proj-name: 'core'
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

