name: CI UI components
on:
  push:
    branches:
      - 'develop'
    paths:
      - 'libs/ui/components/**'
  pull_request:
    paths:
      - 'libs/ui/components/**'

jobs:
  ci-develop:
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [develop]
        with:
          fetch-depth: 0
      - uses: ./.github/actions/ci
        name: Running CI on a push
        with:
          proj-name: ui-components
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  ci-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout [develop]
        with:
          fetch-depth: 0
      - uses: ./.github/actions/ci
        name: Running CI on a pull request
        with:
          proj-name: ui-components
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
